name: Build

on:
  push:
  pull_request:
  schedule:
    - cron: "15 5 * * *"

jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/awinterstein/zephyr-build:main
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update west workspace
        shell: bash
        run: west update

      - name: Build application
        shell: bash
        run: west build -b nucleo_g474re application --build-dir build/nucleo_g474re

      - name: Check coding style
        shell: bash
        run: west clang-format

      - name: Build and run tests
        shell: bash
        run: west twister -T application/tests/ -O build/twister -c

      - name: Publish test results in Github
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: build/twister/twister_suite_report.xml

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          files: build/twister/twister_suite_report.xml
          token: ${{ secrets.CODECOV_TOKEN }}
